[package]
name = "sifr-demo-http"
version = "0.1.0"
edition = "2024"
include = [
  "Cargo.toml",
  "Cargo.lock",
  "sifr.toml",
  "sifr/**/*.sifr",
  "src/**/*.rs",
  "README.md",
  "LICENSE"
]

[package.metadata.sifr]
manifest = "sifr.toml"

[dependencies]
sifr-demo-json = { git = "https://github.com/sifr-lang/sifr-demo-json", tag = "v0.1.0" }
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
